name: Create Win Store Release File on Release
on:
  release:
    types: [published]
  workflow_dispatch:
    inputs: null

jobs:
  windows-store-artifact:
    runs-on: windows-latest

    if: "!github.event.release.prerelease"

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Load Electron Builder Windows Store Config
        run: echo $WIN_STORE_ELECTRON_BUILDER_YML | base64 --decode > electron-builder.yaml
        env:
          WIN_STORE_ELECTRON_BUILDER_YML: ${{secrets.WIN_STORE_ELECTRON_BUILDER_YML}}

      - name: Load Electron Builder Windows Store Config
        id: write_file
        uses: timheuer/base64-to-file@v1.0.3
        with:
          fileName: electron-builder.yaml
          encodedString: ${{ secrets.WIN_STORE_ELECTRON_BUILDER_YML }}

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install yarn packages
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install

      - name: Lint
        run: yarn lint

      - name: Test Unit
        run: yarn test

      - name: Build Frontend & Electron
        run: yarn build

      - name: Build/Release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          build_script_name: empty
          release: false
          github_token: ${{ secrets.github_token }}

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: WinStoreReleas
          path: app-builds/*.appx
