name: "Lint & Test PRs"

on: [pull_request]

jobs:
  test-on-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: NPM or Yarn install with caching
        uses: bahmutov/npm-install@v1.1.0

      - run: yarn lint
      - run: yarn test
      - run: yarn e2e


